### PR TITLE
Use system language for language names

### PR DESCRIPTION
**Pull request by Eitot**

### CODE REVIEW

**Comment by IngmarStein** [comment]
Looks good, thank you! Did you use some tool to find the (now) unused localized strings?

**Comment by IngmarStein** [comment]
It seems like all strings files have been converted from UTF-16 to UTF-8:
```
en.lproj/Localizable.strings: UTF-8 Unicode c program text
```
The Xcode project is configured to interpret the files as UTF-16 as Apple recommends in https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html (*Note: It is recommended that you save strings files using the UTF-16 encoding, which is the default encoding for standard strings files.*)
Could you please re-save all strings files as UTF-16 and create a new PR?

**Comment by Eitot** [comment]
I think that’s because my Xcode is still set to UTF-8. I’ll reformat them.

There is a new translation tool in Xcode 6. When you select the project and go to Editor > Export For Localization… and then import those files again using Import Localizations…, Xcode will generate new string files in the process and drop obsolete ones. However, new translations need to be added to the XLIFF files first before importing, otherwise they are not added as strings on import. It’s a buggy feature though, Xcode sometimes crashes and doesn’t accept single quotes in strings, but it’s better than nothing.

**Comment by IngmarStein** [comment]
It's ok, I've fixed it in the meantime.

**Comment by Eitot** [comment]
Thanks. I’ve looked into this and noticed that the new localisation function only exports UTF-8. Importing these files will scramble the UTF-16 strings files, hence why they were replaced with new UTF-8 files.

**Pull request merged**
