### PR TITLE
Monolingual Persian/Farsi Translation

### PR DESCRIPTION
**Pull request by paymon23**
A complete translation of Monolingual in Persian/Farsi.

### CODE REVIEW

**Comment by IngmarStein** [comment]
Thanks! The submodule `CommandLine` should not be deleted, though. Please adjust PR and I'll merge.

**Comment by paymon23** [comment]
Apologies Ingmar but I've hit a problem. It was not my intention to touch the submodule command line, for some reason this change occurs even when I would like to create a new pull request. Attached is the error message I'm getting when I want to discard this 'forced' change. 

I'm new to Github so sorry about this issue.

screen shot 2017-03-06 at 19 50 21

**Comment by IngmarStein** [comment]
Not sure about the GitHub GUI, but you should have run `git submodule update --init --recursive` in your forked repo. Did you delete the repo used to create this PR ("unknown repository")? The best is probably to try again and recreate your changes on the current HEAD.

**Comment by paymon23** [comment]
I believe the issue is now fixed and I created a new PR here - https://github.com/IngmarStein/Monolingual/pull/114

**Pull request closed without merging**
